version: "3.9"
services:
    nginx_server:
        container_name: nginx_server
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/app
            - ./.devops/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.devops/nginx/sites/:/etc/nginx/sites-available
            - ./.devops/nginx/conf.d/:/etc/nginx/conf.d
            - ./.devops/nginx/logs/:/var/log/nginx/
        depends_on:
            - php-fpm
        networks:
            - phpfpm-network

    # - ./app:/var/www/app  ---> volumes need to be the same for nginx and fpm like
    php-fpm:
        container_name: php-fpm
        build:
            context: ./app
        volumes:
            - ./app:/var/www/app
            - ./.devops/php-fpm/php.ini:/usr/local/etc/php/php.ini
        networks:
            - phpfpm-network
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal, remote_port=9001
          
          #For Windows and macOS, replace the line below with `host.docker.internal`, which will automatically resolve to the internal address of the host Docker is running on.
          #For Linux, replace the line below with your hostname, which you can obtain by executing `hostname` in Terminal.
          #XDEBUG_CONFIG: remote_host=<host.docker.internal or your hostname>

          #For macOS, if you use a local Homebrew php-fpm installation, port `9000` (which is the default debugging port) may become occupied. PhpStorm will remain silent on starting listening for incoming connections. If this is the case, in the Settings | Languages & Frameworks | PHP | Debug, set the Debug port to 9001, and use the following configuration line instead.

          #XDEBUG_CONFIG: remote_host=host.docker.internal, remote_port=9001

networks:
    phpfpm-network:
        driver: bridge


# Testing in http://localhost/test.php
# mirrored volumes in docker is live reloading chages support.
# nginx depends_on php_fpm, and not is the opposite

